name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: 1 1 * * *

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm install
    - run: npm test
    - run: npm run build
    - run: mkdir build
    - run: cp css build && cp js build && cp Icon* build && cp manifest.json build && cp *.html build
    - uses: actions/upload-artifact@v2
      with:
        name: NHentaiDownloader.zip
        path: ./build
        retention-days: 2
